global:
  resolve_timeout: 3m

templates:
  - /alertmanager/*.tmpl

route:
  receiver: alerta
  repeat_interval: 120m
  group_by: [instance]
  group_wait: 60s
  group_interval: 60s
  routes:
  - receiver: alerta
    repeat_interval: 1m
    continue: true
  - receiver: slack
    match_re: {severity: critical|major}
    continue: true

inhibit_rules:
  - source_match:
      severity: critical
    target_match_re:
      severity: major|minor|warning
    equal: [alertname, instance]
  - source_match:
      severity: major
    target_match_re:
      severity: minor|warning
    equal: [alertname, instance]
  - source_match:
      severity: minor
    target_match:
      severity: warning
    equal: [alertname, instance]

receivers:
  - name: alerta
    webhook_configs:
    - url: http://alerta:8080/api/webhooks/prometheus?api-key=
      send_resolved: true
  - name: slack
    slack_configs:
    - api_url: 'https://hooks.slack.com/services/dasdasdasdsasds'
      send_resolved: true
