global:
  scrape_interval:     30s
  evaluation_interval: 30s
  scrape_timeout:      30s
  external_labels:
    workspace: infra
    client: 1win
    responsible: 1win-devops
    monitor: monitoring-prod

rule_files:
  - blackbox.rules.yml
  - certs.rules.yml
  - domains.rules.yml
  - nodes.rules.yml
  - services.rules.yml
  - rabbit.rules.yml

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'example.com'


scrape_configs:
  - job_name: monitoring
    static_configs:
    - targets: ['192.168.12.12:9100']
      labels:
        hostname: 'node_name'
